
server:
  port: 8080

spring:
  application:
    name: MiniBite
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/minibite?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ssafy  # 본인의 MySQL 아이디
    password: ssafy # 본인의 MySQL 비밀번호

  

  # 파일 업로드 설정 (프로필 이미지 등)
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  mapper-locations: classpath:mappers/*.xml  # XML 파일 위치 지정
  configuration:
    map-underscore-to-camel-case: true       # DB(snake_case) -> Java(camelCase) 자동 변환
    jdbc-type-for-null: NULL                 # 파라미터가 null일 때 처리

logging:
  level:
    root: INFO
    com.ssafy.minibite: DEBUG                # 우리 패키지 로그는 자세히
    org.hibernate.SQL: DEBUG                 # (JPA 쓸 때 유용하지만 일단 둠)
    com.zaxxer.hikari: INFO